language: node_js
node_js: '16.15.0' # .nvmrc
os: linux

before_script:
  - nvm use
  - npm i
  - npm run parse

git:
  depth: 3

jobs:
  include:
    - stage: release
      node_js: '16.15.0' # .nvmrc

      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

notifications:
  email:
    on_success: change
    on_failure: change
