language: node_js
node_js: '16.15.0' # .nvmrc
os: linux

before_script:
  - nvm use
  - npm i
  - npm run parse

git:
  depth: 3

notifications:
  email:
    on_success: change
    on_failure: change
